language: ruby

services:
  - postgresql
  - redis-server

rvm:
  - 2.3.1

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=3.3.1 DB=postgresql

before_install:
  - export ES_HOME=/usr/share/elasticsearch
  - sudo wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.1.0.deb
  - sudo service elasticsearch stop
  - sudo dpkg -i elasticsearch-1.1.0.deb
  - sudo $ES_HOME/bin/plugin -install elasticsearch/elasticsearch-mapper-attachments/2.0.0
  - sudo service elasticsearch start
  - sleep 3
  - export PLUGIN_NAME=redmine_elasticsearch
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - git clone --depth=1 https://github.com/Restream/redmine_resque.git $REDMINE_PATH/plugins/redmine_resque
  - echo "gem 'iconv'" >> $REDMINE_PATH/Gemfile
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME RUBYOPT="-W0"
