language: ruby

services:
  - postgresql

rvm:
  - 1.9.3
  - 2.0.0

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=2.1.6 DB=postgresql
  - REDMINE_VER=2.2.4 DB=postgresql
  - REDMINE_VER=2.3.4 DB=postgresql
  - REDMINE_VER=2.4.2 DB=postgresql

matrix:
  exclude:
    - rvm: 2.0.0
      env: REDMINE_VER=2.1.6
      gemfile: $REDMINE_PATH/Gemfile
    - rvm: 2.0.0
      env: REDMINE_VER=2.2.4
      gemfile: $REDMINE_PATH/Gemfile

before_install:
  - export PLUGIN_NAME=redmine_elasticsearch
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database-$DB-travis.yml $REDMINE_PATH/config/database.yml
  - git clone --depth=1 https://github.com/Undev/redmine_sidekiq.git $REDMINE_PATH/plugins/redmine_sidekiq
  - cd $REDMINE_PATH

before_script:
  - rake db:create
  - rake db:migrate
  - rake redmine:plugins:migrate

script:
  - rake redmine:plugins:test NAME=$PLUGIN_NAME
